#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "Copying 'initial' to 0"
cp -r initial 0

echo "Running blockMesh"
runApplication blockMesh

echo "Running setSolidFraction"
runApplication setSolidFraction

echo "Running transformPoints with rotation"
runApplication transformPoints "rotate=((0 1 0) (0 0 1))"

echo "Decomposing domain for parallel run"
decomposePar -force
mpirun -np 27 laserbeamFoam -parallel
#mpirun -np 8 laserbeamFoam -parallel
#mpirun -np 16 laserbeamFoam -parallel

echo "Reconstructing fields from parallel run"
reconstructPar

foamToVTK
